name: Header checks

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
jobs:
  windows:
    name: Full unit tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    
    - name: Download & install RTools
      run: |
        Invoke-WebRequest -Uri https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe -OutFile ./R40.exe
        Start-Process -FilePath ./R40.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
      shell: powershell
    
    - name: PATH Setup
      run: |
        echo "::add-path::C:/rtools40/usr/bin"
        echo "::add-path::C:/rtools40/mingw64/bin"
      shell: powershell
    
    - name: Print g++ version and path
      run: |
        g++ --version
        Get-Command g++ | Select-Object -ExpandProperty Definition
      shell: powershell
    
    - name: Print mingw32-make version
      run: |
        mingw32-make --version
        Get-Command mingw32-make | Select-Object -ExpandProperty Definition
      shell: powershell

    - name: Build Math libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
      
    - name: Run header tests
      shell: powershell
      run: make -j2 test-headers
