name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/bin"
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/mingw_64/bin"
    - name: Check g++ version
      shell: powershell
      run: g++ --version
    - name: Check mingw32-make version
      shell: powershell
      run: mingw32-make --version
    - name: Run tests
      shell: powershell
      run: python runTests.py -j8 test/unit