name: OpenCL

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: test/unit/math/opencl
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y ocl-icd-opencl-dev clinfo beignet

    - name: Print system info
      run: |
        g++ --version
        make --version
        clinfo

    - name: Run tests
      run: |
        ./runTests.py test/unit/math/prim/fun/add_test.cpp

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'
